import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import WaitlistManager from "./components/WaitlistManager";
import { submitWaitlist } from "@/app/actions/waitlist";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header">
          <div className="nav-container">
            <Link href="/" className="logo">CalvinBall Technologies</Link>
            <nav>
              <ul className="nav-menu">
                <li><Link href="/">Overview</Link></li>
                <li><Link href="/#product">Product</Link></li>
                <li><Link href="/#team">Team</Link></li>
                <li><Link href="/#experts">Experts</Link></li>
                <li><Link href="/careers">Career</Link></li>
              </ul>
            </nav>
            <Link href="#waitlist" className="footer-cta">
             Join The Waitlist
            <span>→</span>
          </Link>
          </div>
        </header>
        {children}
        <footer className="footer">
          <div className="footer-container">
            <div className="footer-content">
              <div className="footer-logo">CalvinBall Technologies</div>
                <Link href="#waitlist" className="footer-cta">
                  Join The Waitlist
                  <span>→</span>
                </Link>
            </div>
            <div className="certifications">
              <div className="cert"><div className="cert-icon" /><span>ISO Certified</span></div>
              <div className="cert"><div className="cert-icon" /><span>SOC Compliant</span></div>
            </div>
            <div className="footer-bottom">
              <p>Copyright © 2024 CalvinBall Technologies. All rights reserved.</p>
            </div>
          </div>
        </footer>
        <WaitlistManager submitWaitlist={submitWaitlist} />
      </body>
    </html>
  );
}
